# Generated by Django 6.0.2 on 2026-02-14 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_surname', models.CharField(max_length=100)),
                ('client_firstname', models.CharField(max_length=100)),
                ('client_patronymic', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('is_busy', models.BooleanField()),
                ('reserved_time', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
            ],
        ),
    ]
